# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.CharField(default='wuxi', max_length=200, null=True)),
                ('rank', models.CharField(max_length=200, null=True)),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('ipaddr', models.CharField(max_length=200, null=True)),
                ('macaddr', models.CharField(max_length=200, null=True)),
                ('cpu', models.CharField(max_length=200, null=True)),
                ('mem', models.CharField(max_length=200, null=True)),
                ('disk', models.CharField(max_length=200, null=True)),
                ('sn', models.CharField(max_length=100, null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
